export default {
    welcomeBack: 'Welcome Back!',
    enterMobileNumber: 'Enter Mobile Number',
    mobileNumber: 'Mobile Number',
    PASSWORD:"Password",
    login: 'Login',
    dontHaveAnAccount: 'Don’t have an Account?',
    register: 'Register',
    otpVerification: 'OTP Verification',
    verificationCodeSendToYourNumber: 'Verification code send to your number',
    didntReceiveTheCode: "Didn't Receive the code?",
    resend: 'RESEND',
    verifyOtp: 'Verify OTP',
    chooseLanguage: 'Choose Language',
    hindi: 'Hindi',
    english: 'English',
    next: 'Next',
    home: 'Home',
    scan: 'Scan',
    scheme: 'Scheme',
    pointRegister: 'Point Register',
    learning: 'Learning',
    cart: 'Cart',
    profile: 'Profile',
    more: 'More',
    hi: 'Hi',
    welcome: 'Welcome!',
    pointSummary: 'Point Summary',
    availabePoints: 'Availabe Points',
    pTS: 'PTS',
    earnedpointsForThisYear: 'Earned points for This year',
    redeemYourPoints: 'redeem your points',
    pointConvertToCash: 'point convert to cash',
    buyNow: 'Buy Now',
    start: 'Start',
    monthlySummary: 'Monthly Summary',
    transactionHistory: 'Transaction History',
    narration: 'Narration',
    debit: 'Debit',
    totalPoints: 'Total Points',
    credit: 'Credit',
    pointToCase: 'Point To Case',
    RS: 'RS',
    areYouConfirm: 'Are you Confirm',
    convertToCash: 'convert to cash?',
    note: 'NOTE',
    thePointIsRedeemIntoCashAfter24hoursInYourBankAcount:
      'The point is redeem into cash after 24 hours in your bank account',
    myProfile: 'My profile',
    pleaseWait: 'Please wait...',
    changeLanguage: 'Change Language',
    BANK_DETAILS: 'Bank Details',
    referral: 'Referral',
    contactUs: 'Contact Us',
    privacyPolicy: 'Privacy Policy',
    termsAndCondition: 'Terms & Condition',
    aboutUs: 'About Us',
    aboutDevice: 'About Device',
    logout: 'Logout',
    masonMeet: 'Mason Meet',
    PROFILE_SETTING: 'PROFILE SETTING',
    masterBuilder: 'Master Builder',
    masterBuilderSilver: 'Master Builder Silver',
    masterBuilderGold: 'Master Builder Gold',
    masterBuilderDiamond: 'Master Builder Diamond',
    address: 'Address',
    phoneNo: 'phone no',
    email: 'Email',
    website: 'Website',
    product: 'Product',
    redeem: 'Redeem',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    aadhaarNumber: 'Aadhaar Number',
    panNumber: 'PAN Number',
    profileDetails: 'Profile Details',
    submit: 'Submit',
    enterFirstname: 'Enter Firstname',
    enterLastname: 'Enter Lastname',
    ENTER_EMAIL: 'Enter Email',
    ENTER_PAN_ID: 'Enter Pan ID',
    FIRST_NAME: 'Firstname',
    LAST_NAME: 'Lastname',
    PAN_ID: 'Pan ID',
    ENTER_BANK_ACCOUNT_NUMBER: 'Enter Bank Account Number',
    ENTER_CONFIRM_BANK_ACCOUNT_NUMBER: 'Enter Confirm Bank Account Number',
    BANK_ACCOUNT_NUMBER: 'Bank  Account Number',
    CONFIRM_BANK_ACCOUNT_NUMBER: 'Confirm Bank Account Number',
    ENTER_IFSC_CODE: 'Enter IFSC code',
    IFSC_CODE: 'IFSC code',
    BANK_ACCOUNT_NAME: 'Bank Account Name',
    ENTER_BANK_ACCOUNT_NAME: 'Enter Bank Account Name',
    ENTER_UPI_PIN: 'Enter Upi Pin',
    UPI_PIN: 'Upi Pin',
    ENTER_QR_CODE: 'Enter QR Code',
    QR_CODE: 'QR Code',
    ENTER_KYC: 'Enter KYC',
    SELECT_DOCUMENT: 'Select document',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    HISTORY: 'History',
    ORDER_DETAILS: 'Order Details',
    YES: 'Yes',
    NO: 'No',
    OK: "Ok",
    ORDER_TRACKING: "Order Tracking",
    PRODUCT_DETAILS: "Product Details",
    SCAN: "Scan",
    PLEASE_ENTER_PHONE_NUMBER: "Please Enter Phone Number",
    PLEASE_ENTER_VALID_PHONE_NUMBER: "Please Enter Valid Phone Number",
    TRACK: "Track",
    SHARE: "Share",
    PLEASE_CHECK_INTERNET: "Please check your internet ",
    SELECT_POINTS: "Select Points",
    STATE: "State",
    PIN_CODE: "Pincode",
    DOB: "Date of birth",
    ENTER_AADHAR: "Enter Aadhar",
    ENTER_PAN_ID: "Enter Pan ID",
    POINTS: "Points",
    UPLOAD_QR_CODE: "Upload Qr code",
    ACCOUNT_HOLDER_NAME: "Account Holder name",
    UPDATE: "Update",
    RETRY: "Retry",
    CANCEL: "Cancel",
    CHOOSE_MONTH: "Choose Month",
    PLACE_YOUR_CAMERA: "Place your camera towards QR code.",
    CONTINUE: "Continue",
    INVALID_QR: "Invalid QR code",
    NOTHING_FOUND: "Nothing found",
    OUT_OF_STOCK: "Out of stock",
    AVAILABLE_SOON: "Available soon",
    LEADER_BOARD: "Leaderboard",
    APP_REQ_CAMERA_PERM: "This app requires camera permission",
    ALLOW: "Allow",
    BANK_DETAILS_UPDATED: "Bank details successfully updated",
    CHANGE_PHOTO: "Change photo",
    UNLOCK_YOUR_EXCLUSIVE: "Unlock Exclusive Rewards: Redeem Your Points",
    MONETIZE_YOUR_LOYALITY: "Unlock the Power of Your Points: Convert Them into Real Cash",
    PEOPLE: "People",
    PEOPLE_DESCRIPTION: "We care deeply about the people we work with and those who have instilled their trust in us. We care about our diligent employees, our forward-thinking partners, and our trusting customers. We acknowledge the demands and requirements our society’s development is contingent upon, and work towards meeting those.",
    PASSION: "Passion",
    PASSION_DESCRIPTION: "Passion is the fuel that drives the engine of success. Our passion defines our mindset and revitalizes our business, encouraging us to widen our horizon and work towards taking our dreams to greater heights.",
    PLACE: "Place",
    PLACE_DESCRIPTION: "We are forever indebted to Mother Nature, and want to ethically and honestly contribute towards building a better place that we can be proud of and where our future generations can thrive without inhibitions.",
    READ_MORE: "Read More",
    WE_ARE: "We are solemnly dedicated to the promise of producing high-quality steel, and making it available to our customers regardless of which part of the country they want to construct their dream.",
    OUR_FOCUS: "Our focus is relentlessly on the needs of our customers and our aim has been to provide them with efficient, reliable and affordable building materials in the form of our TUFCON 600 HCR TMT Rebars. We have immense belief in our product, and this confidence stems from the latest state-of-the-art German technology, which is the secret to our highest possible quality of TMT Re-bars. As a company, we’ll always stand committed to our objective.",
    ACCOUNT_NUMBER:"Account number",
    BANK_NAME:"Account number",
    ACCOUNT_NAME:"Account name",
    IFSC:"Ifsc",
    UPI:"Upi",
    BANK_QR:"Bank qr",
    ARE_YOU_SURE_WANT_REDEEM:"Are you sure you want to redeem?",
    profile_photo_updated:"Profile photo updated",
    SEARCH_HERE:"Search here",
    ENTER_DISTRICT: "Enter District",
    DISTRICT: "District",
    CHOOSE_STATE: "Choose State",
    CHOOSE_DISTRICT: "Choose District",
    ENTER_CITY: "Enter City",
    CITY: "City",
    PLEASE_SELECT_STATE_FIRST: "Please select state first",
    REGISTER_NOW: "Register Now",
    GET_STARTED: "Get Started",
    ENTER_FIRST_NAME: "Enter First Name",
    FIRST_NAME: "First name",
    LAST_NAME: "Last name",
    ENTER_LAST_NAME: "Enter Last Name",
    ENTER_MIDDLE_NAME:"Enter Middle Name",
    MIDDLE_NAME:"Middle name",
    ENTER_ADDRESS:"Enter Address",
    ALL_FIELDS_ARE_REQ: "All fields are required",
    FILL_ALL_REQUIRED_FIELDS: "Please fill all required fields",
    NEW_Registration:"New Registration",
    UPLOAD_AADHAR:"Upload Aadhar",
    FRONT:"Front",
    BACK:"Back",
    NEW_USERS:"New Users",
    ENTER_PINCODE:"Enter Pincode",
    CAMERA:"Camera",
    GALLERY:"Gallery",
    IMAGE_NOT_AVAILABLE:"Image not available"
  };
  